{{- range $i, $gateway := .Values.gateways }}
{{- if $gateway.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    {{- if $gateway.service }}
    kubernetes:
      envoyService:
        {{- with $gateway.service.labels }}
        labels:
          {{- (tpl (. | toYaml | toString ) $) | nindent 10 }}
        {{- end }}
        annotations:
          external-dns.alpha.kubernetes.io/hostname: {{ $gateway.dnsName }}.{{ $gateway.overrideBaseDomain | default $.Values.baseDomain }}
          giantswarm.io/external-dns: managed
          {{- with $gateway.service.annotations }}
          {{- (tpl (. | toYaml | toString ) $) | nindent 10 }}
          {{- end }}
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- with $gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.className }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: gateway-{{ $gateway.name }}
      namespace: {{ $.Release.Namespace }}
  listeners:
    {{- range $k, $l:= $gateway.listeners }}
    - name: {{ $l.name }}
      protocol: {{ $l.protocol }}
      port: {{ $l.port }}
      {{- with $l.allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $l.hostname }}
      hostname: {{ tpl (. | quote) $ }}
      {{- end }}
      {{- with $l.tls }}
      tls:
        mode: {{ .mode }}
        {{- if or (.certificateRefs) ($gateway.certificate.enabled) }}
        certificateRefs:
        {{- if and (eq .mode "Terminate") ($gateway.certificate.enabled) }}
        - kind: Secret
          name: gateway-{{ $gateway.name }}-tls
        {{- end }}
        {{- range .certificateRefs }}
        - kind: Secret
          name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
