{{- range $i, $gateway := .Values.gateways }}
{{- if $gateway.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-gateway
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  podMetricsEndpoints:
  - honorLabels: true
    interval: 60s
    metricRelabelings: []
    path: /stats/prometheus
    port: metrics
    relabelings:
    - action: replace
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: {{ $gateway.name }}
{{- end }}
{{- end }}
