package basic

import (
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/giantswarm/apptest-framework/v3/pkg/state"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	cr "sigs.k8s.io/controller-runtime/pkg/client"
)

// gatewayMonitoringTests verifies PodMonitor and PodLogs resources are generated by Kyverno
// for the gateway, enabling Prometheus scraping and log aggregation for observability.
func gatewayMonitoringTests() {
	wcName := state.GetCluster().Name
	wcClient, _ := state.GetFramework().WC(wcName)

	By("checking PodMonitor giantswarm-default is generated in envoy-gateway-system")
	podMonitor := &unstructured.Unstructured{}
	podMonitor.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "monitoring.coreos.com",
		Version: "v1",
		Kind:    "PodMonitor",
	})
	Eventually(func() error {
		return wcClient.Get(state.GetContext(), cr.ObjectKey{
			Name:      "giantswarm-default",
			Namespace: "envoy-gateway-system",
		}, podMonitor)
	}).
		WithTimeout(5 * time.Minute).
		WithPolling(5 * time.Second).
		Should(Succeed())

	By("checking PodLogs giantswarm-default is generated in envoy-gateway-system")
	podLogs := &unstructured.Unstructured{}
	podLogs.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "monitoring.grafana.com",
		Version: "v1alpha2",
		Kind:    "PodLogs",
	})
	Eventually(func() error {
		return wcClient.Get(state.GetContext(), cr.ObjectKey{
			Name:      "giantswarm-default",
			Namespace: "envoy-gateway-system",
		}, podLogs)
	}).
		WithTimeout(5 * time.Minute).
		WithPolling(5 * time.Second).
		Should(Succeed())
}

// gatewayKyvernoRegenerationTest confirms Kyverno automatically recreates deleted monitoring resources,
// validating the ClusterPolicy correctly enforces PodMonitor generation even if manually deleted.
func gatewayKyvernoRegenerationTest() {
	wcName := state.GetCluster().Name
	wcClient, _ := state.GetFramework().WC(wcName)

	podMonitorGVK := schema.GroupVersionKind{
		Group:   "monitoring.coreos.com",
		Version: "v1",
		Kind:    "PodMonitor",
	}
	key := cr.ObjectKey{Name: "giantswarm-default", Namespace: "envoy-gateway-system"}

	By("recording the creation timestamp of the existing PodMonitor giantswarm-default")
	original := &unstructured.Unstructured{}
	original.SetGroupVersionKind(podMonitorGVK)
	Expect(wcClient.Get(state.GetContext(), key, original)).To(Succeed())
	originalTS := original.GetCreationTimestamp()

	By("deleting the Kyverno-generated PodMonitor giantswarm-default")
	grace := int64(0)
	Expect(wcClient.Delete(state.GetContext(), original, &cr.DeleteOptions{
		GracePeriodSeconds: &grace,
	})).To(Succeed())

	By("waiting for Kyverno to regenerate the PodMonitor giantswarm-default")
	recreated := &unstructured.Unstructured{}
	recreated.SetGroupVersionKind(podMonitorGVK)
	Eventually(func() error {
		if err := wcClient.Get(state.GetContext(), key, recreated); err != nil {
			return err
		}
		newTS := recreated.GetCreationTimestamp()
		if !newTS.After(originalTS.Time) {
			return fmt.Errorf("PodMonitor not yet recreated (same or older creation timestamp)")
		}
		return nil
	}).
		WithTimeout(5 * time.Minute).
		WithPolling(5 * time.Second).
		Should(Succeed())
}
