{{- range $i, $gateway := .Values.gateways }}
{{- if and $gateway.enabled }}
{{- range $j, $listener := $gateway.listeners }}
{{- if and $listener.certificate $listener.certificate.enabled (eq $listener.protocol "HTTPS") }}
---
{{ include "listener.certificate" (dict "gateway" $gateway "listener" $listener "root" $) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
