{{- range $i, $gateway := .Values.gateways }}
{{- if and $gateway.enabled }}
{{- range $j, $listener := $gateway.listeners }}
{{- if and $listener.dnsEndpoints $listener.dnsEndpoints.enabled }}
{{- $baseDomain := include "listener.baseDomain" (dict "gateway" $gateway "listener" $listener "root" $) }}
{{- $subdomains := list }}
{{- range $k, $subdomain := $listener.subdomains }}
{{- $subdomains = append $subdomains (printf "%s.%s" $subdomain $baseDomain) -}}
{{- end }}
{{- if $subdomains }}
---
{{ include "listener.dnsEndpoint" (dict "gateway" $gateway "listener" $listener "root" $ "records" $subdomains) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
